### ISSUE TITLE
User Authentication

### ISSUE THREAD

**Issue by joshmanders** [aniftyco/saas-starter#1]
Most apps will need authentication, so we need to implement some basic authentication measures.

## Todo:
- [x] Sign Up page
- [x] Sign In page
- [ ] Forgot Password page
- [ ] Reset Password page
- [x] Dashboard page
- [x] Sign Out page

**Comment by joshmanders** [comment]
Implemented Sign up, sign in, sign out and a basic dashboard page already in 6e79c18
